In [20]:
import pandas as pd

In [21]:
folder = './Data Formated'
files = ['investment_trends.csv',
        'NEX_returns.csv',
        'policies.csv']

In [22]:
df1 = pd.read_csv(f'{folder}/{files[0]}', index_col=0)
df2 = pd.read_csv(f'{folder}/{files[1]}', index_col=0)

df1.merge(df2, on=['Country', 'Year'])

,Country,Year,Government R&D,Corporate R&D,Venture capital,Private equity expansion capital,Public markets,Asset finance,Asset Finance minus Re-invested equity,Small distributed capacity,Private equity buy-outs,Public markets investor exits,Corporate M&A,Project acquisition & refinancing,Total: M&A/ buy-outs etc.,NEX Returns
0,China,2000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000
1,China,2001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000
2,China,2002,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000
3,China,2003,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000
4,China,2004,0.076,0.076,0.016,0.012,0.012,1.284,1.280,0.320,0.032,0.016,0.088,0.204,0.340,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,United States,2015,1.056,0.984,0.336,0.432,2.880,64.248,62.640,7.824,0.864,0.360,4.416,20.304,25.944,-9.891067
76,United States,2016,1.275,1.075,0.200,0.425,1.550,61.875,60.850,8.125,0.800,1.600,7.375,23.700,33.475,-9.514435
77,United States,2017,1.224,1.656,0.192,0.168,1.344,65.424,64.728,10.200,2.544,0.672,3.192,28.704,35.088,65.658118
78,United States,2018,1.320,1.872,0.048,0.528,1.440,58.080,56.688,9.168,3.120,0.024,3.504,29.712,36.360,-3.140805
79,United States,2019,1.368,1.848,0.048,0.432,1.584,55.224,54.408,12.504,0.768,0.000,3.288,20.112,24.168,68.005015

In [29]:
df = pd.DataFrame()

for file in files:
    file = f'{folder}/{file}'
    
    if df.size == 0:
        df = pd.read_csv(file, index_col=0)

        continue

    df2 = pd.read_csv(file, index_col=0)
    df = df.merge(df2, on=['Country', 'Year'])
    
df

,Country,Year,Government R&D,Corporate R&D,Venture capital,Private equity expansion capital,Public markets,Asset finance,Asset Finance minus Re-invested equity,Small distributed capacity,Private equity buy-outs,Public markets investor exits,Corporate M&A,Project acquisition & refinancing,Total: M&A/ buy-outs etc.,NEX Returns,Number of policies
0,China,2000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,0
1,China,2001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,0
2,China,2002,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,1
3,China,2003,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,1
4,China,2004,0.076,0.076,0.016,0.012,0.012,1.284,1.280,0.320,0.032,0.016,0.088,0.204,0.340,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,United States,2015,1.056,0.984,0.336,0.432,2.880,64.248,62.640,7.824,0.864,0.360,4.416,20.304,25.944,-9.891067,0
76,United States,2016,1.275,1.075,0.200,0.425,1.550,61.875,60.850,8.125,0.800,1.600,7.375,23.700,33.475,-9.514435,1
77,United States,2017,1.224,1.656,0.192,0.168,1.344,65.424,64.728,10.200,2.544,0.672,3.192,28.704,35.088,65.658118,0
78,United States,2018,1.320,1.872,0.048,0.528,1.440,58.080,56.688,9.168,3.120,0.024,3.504,29.712,36.360,-3.140805,1
79,United States,2019,1.368,1.848,0.048,0.432,1.584,55.224,54.408,12.504,0.768,0.000,3.288,20.112,24.168,68.005015,0

In [ ]:
df.to_csv('')